language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "8"
  - "10"
  - "12"

before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

script:
  - npm run eslint
  - npm run jscs
  - npm run test-cov

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
